# -------------------------------------------------------------------------------------------------------------------
# Author                       Version          Created_Date              JIRA                 Description
# {{cookiecutter.author}}                    V1.0           2022-03-13             {{cookiecutter.jira_story_nbr}}      {{cookiecutter.project_description}}
# -------------------------------------------------------------------------------------------------------------------


version: "3.2"

services:
  <service_name>::
    container_name: {{ cookiecutter.project_name }}
    command: tail -f /dev/null # keep container running in background
    restart: on-failure
    build: .
    environment:

    env_file:
      - .env
    volumes:
      - ./{{ cookiecutter.project_name }}:/

